. ~/venv/bin/activate

alias rs='pushd ~/src ; python manage.py runserver --settings=cah.settings.vagrant ; popd'
alias syncdb='pushd ~/src ; python manage.py syncdb --settings=cah.settings.vagrant ; popd'
